// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// import CarParkController from "./car_park_controller.js"
// application.register("car-park", CarParkController)

import controllers from "./**/*_controller.js"
controllers.forEach((controller) => {
    application.register(controller.name, controller.module.default)
})
